services:
  rentaldb:
    image: postgres:16-alpine
    container_name: rental_postgres_db
    env_file:
      - .env
    volumes:
      - rental_postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - scooter_network

  app:
    build: .
    depends_on:
      - rentaldb
    env_file:
      - .env
    ports:
      - "8020:8000"
    networks:
      - scooter_network
    volumes:
      - .:/src # бинд-маунт (отключать при деплое)

networks:
  scooter_network:
    driver: bridge


volumes:
  rental_postgres_data:
    driver: local
